spring:
  application:
    name: Routine-Pusher

  datasource:
    url: jdbc:postgresql://localhost:5432/routine-pusher
    username: postgres
    password: PgreWsl
    hikari:
      pool-size: 30
    driver-class-name: org.postgresql.Driver
    quartz:
      job-store-type: jdbc
      properties:
        org.quartz.threadPool:
          threadCount: 5

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  rabbitmq:
    host: localhost
    port: 15672
    username: guga
    password: gugaMQ

rabbitmq:
  queue:
    name: mobile_notification
    json: mobile_notification_json-name
  exchange:
    name: mobile_notification_exchange
  routing:
    key: mobile_notification_routing-key
    json: mobile_notification_json-key